"""Generate Liquibase seed SQL from legacy Clinical Chart CSV (run from repo root or any cwd)."""
from __future__ import annotations

import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "src/main/resources/db/changelog/Clinical Chart Data(in).csv"
OUT = ROOT / "src/main/resources/db/changelog/changesets/098-clinical-chart-seed-generated.sql"


def esc(s: str | None) -> str:
    if s is None:
        return ""
    t = str(s).strip()
    if t.upper() == "NULL":
        return ""
    return t.replace("'", "''")


def parse_charge(raw: str | None) -> str:
    if not raw or not str(raw).strip():
        return "NULL"
    try:
        return str(float(str(raw).strip().replace(",", "")))
    except ValueError:
        return "NULL"


def main() -> None:
    rows: list[tuple] = []
    with SRC.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            lid = int(row["id"])
            pcode = esc(row.get("PCode", "") or "")
            desc = esc(row.get("Description", "") or "")
            charge_sql = parse_charge(row.get("Charge"))
            dept = esc(row.get("DeptName", "") or "")
            subd = esc(row.get("SubDeptName", "") or "")
            ssd = esc(row.get("SubSubDeptName", "") or "")
            rg = esc(row.get("ReportGroupName", "") or "")
            try:
                ot = int(row.get("OutTest", "0") or 0)
            except ValueError:
                ot = 0
            try:
                st = int(row.get("Status", "1") or 1)
            except ValueError:
                st = 1
            rows.append((lid, pcode, desc, charge_sql, dept, subd, ssd, rg, ot, st))

    lines: list[str] = [
        "-- GENERATED by scripts/generate_clinical_chart_seed.py — do not edit by hand.",
        "",
    ]
    chunk_size = 400
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i : i + chunk_size]
        value_lines: list[str] = []
        for lid, pcode, desc, charge_sql, dept, subd, ssd, rg, ot, st in chunk:
            csql = charge_sql if charge_sql == "NULL" else charge_sql
            value_lines.append(
                f"({lid},'{pcode}','{desc}',{csql},'{dept}','{subd}','{ssd}','{rg}',{ot},{st})"
            )
        lines.append(
            "INSERT INTO hospital.clinical_chart_items "
            "(legacy_row_id,pcode,description,charge,dept_name,sub_dept_name,sub_sub_dept_name,"
            "report_group_name,out_test,status_legacy) VALUES"
        )
        lines.append(",\n".join(value_lines))
        lines.append("ON CONFLICT (legacy_row_id) DO NOTHING;")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} rows -> {OUT}")


if __name__ == "__main__":
    main()
