export const BANGLADESH_DISTRICTS: readonly string[] = [
  'Bagerhat',
  'Bandarban',
  'Barguna',
  'Barishal',
  'Bhola',
  'Bogra',
  'Brahmanbaria',
  'Chandpur',
  'Chapai Nawabganj',
  'Chattogram',
  'Chuadanga',
  'Comilla',
  "Cox's Bazar",
  'Dhaka',
  'Dinajpur',
  'Faridpur',
  'Feni',
  'Gaibandha',
  'Gazipur',
  'Gopalganj',
  'Habiganj',
  'Jamalpur',
  'Jashore',
  'Jhalokati',
  'Jhenaidah',
  'Joypurhat',
  'Khagrachhari',
  'Khulna',
  'Kishoreganj',
  'Kurigram',
  'Kushtia',
  'Lakshmipur',
  'Lalmonirhat',
  'Madaripur',
  'Magura',
  'Manikganj',
  'Meherpur',
  'Moulvibazar',
  'Munshiganj',
  'Mymensingh',
  'Naogaon',
  'Narail',
  'Narayanganj',
  'Narsingdi',
  'Natore',
  'Netrokona',
  'Nilphamari',
  'Noakhali',
  'Pabna',
  'Panchagarh',
  'Patuakhali',
  'Pirojpur',
  'Rajbari',
  'Rajshahi',
  'Rangamati',
  'Rangpur',
  'Satkhira',
  'Shariatpur',
  'Sherpur',
  'Sirajganj',
  'Sunamganj',
  'Sylhet',
  'Tangail',
  'Thakurgaon',
];

export const BANGLADESH_THANAS_BY_DISTRICT: Readonly<Record<string, readonly string[]>> = {
  Dhaka: [
    'Adabor',
    'Badda',
    'Bangshal',
    'Cantonment',
    'Chawkbazar',
    'Demra',
    'Dhanmondi',
    'Gendaria',
    'Gulshan',
    'Hazaribagh',
    'Jatrabari',
    'Kadamtali',
    'Kamrangirchar',
    'Khilgaon',
    'Khilkhet',
    'Kotwali',
    'Lalbagh',
    'Mirpur',
    'Mohammadpur',
    'Motijheel',
    'New Market',
    'Pallabi',
    'Paltan',
    'Ramna',
    'Rampura',
    'Sabujbagh',
    'Shah Ali',
    'Shahbagh',
    'Sher-e-Bangla Nagar',
    'Sutrapur',
    'Tejgaon',
    'Turag',
    'Uttara',
    'Wari',
  ],
  Gazipur: ['Gazipur Sadar', 'Kaliakair', 'Kaliganj', 'Kapasia', 'Sreepur'],
  Narayanganj: ['Araihazar', 'Bandar', 'Narayanganj Sadar', 'Rupganj', 'Sonargaon'],
  Narsingdi: ['Belabo', 'Manohardi', 'Narsingdi Sadar', 'Palash', 'Raipura', 'Shibpur'],
  Chattogram: [
    'Anwara',
    'Banshkhali',
    'Boalkhali',
    'Chandanaish',
    'Fatikchhari',
    'Hathazari',
    'Lohagara',
    'Mirsharai',
    'Patiya',
    'Rangunia',
    'Raozan',
    'Sandwip',
    'Satkania',
    'Sitakunda',
  ],
  Comilla: [
    'Barura',
    'Brahmanpara',
    'Burichong',
    'Chandina',
    'Chauddagram',
    'Daudkandi',
    'Debidwar',
    'Homna',
    'Laksam',
    'Meghna',
    'Monoharganj',
    'Muradnagar',
  ],
  Rajshahi: ['Bagha', 'Bagmara', 'Charghat', 'Durgapur', 'Godagari', 'Mohanpur', 'Paba', 'Puthia', 'Tanore'],
  Khulna: ['Batiaghata', 'Dacope', 'Dumuria', 'Dighalia', 'Koyra', 'Paikgachha', 'Phultala', 'Rupsa', 'Terokhada'],
  Sylhet: ['Balaganj', 'Beanibazar', 'Bishwanath', 'Companyganj', 'Fenchuganj', 'Golapganj', 'Gowainghat', 'Jaintiapur', 'Kanaighat', 'Zakiganj'],
  Barishal: ['Agailjhara', 'Babuganj', 'Bakerganj', 'Banaripara', 'Gournadi', 'Hizla', 'Mehendiganj', 'Muladi', 'Wazirpur'],
  Mymensingh: ['Bhaluka', 'Dhobaura', 'Fulbaria', 'Gafargaon', 'Gauripur', 'Haluaghat', 'Ishwarganj', 'Muktagachha', 'Nandail', 'Phulpur', 'Trishal'],
  Rangpur: ['Badarganj', 'Gangachara', 'Kaunia', 'Mithapukur', 'Pirgachha', 'Pirganj', 'Rangpur Sadar', 'Taraganj'],
};
