package com.easyops.hr.service;

import com.easyops.hr.entity.PayrollRun;
import com.easyops.hr.repository.EmployeeRepository;
import com.easyops.hr.repository.PayrollDetailRepository;
import com.easyops.hr.repository.PayrollRunRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDate;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class PayrollServiceTest {

    @Mock
    private PayrollRunRepository payrollRunRepository;
    @Mock
    private PayrollDetailRepository payrollDetailRepository;
    @Mock
    private EmployeeRepository employeeRepository;
    private PayrollService payrollService;

    private UUID runId;
    private UUID orgId;

    @BeforeEach
    void setUp() {
        runId = UUID.randomUUID();
        orgId = UUID.randomUUID();
        payrollService = new PayrollService(
                payrollRunRepository,
                payrollDetailRepository,
                employeeRepository,
                null
        );
    }

    @Test
    void updatePayrollRun_rejectsDirectStatusChange() {
        PayrollRun existing = new PayrollRun();
        existing.setPayrollRunId(runId);
        existing.setOrganizationId(orgId);
        existing.setStatus("DRAFT");

        PayrollRun updates = new PayrollRun();
        updates.setStatus("APPROVED");

        when(payrollRunRepository.findById(runId)).thenReturn(Optional.of(existing));

        assertThatThrownBy(() -> payrollService.updatePayrollRun(runId, updates))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("Payroll status cannot be updated via update endpoint");
    }

    @Test
    void createPayrollRun_setsDraftDefaultsAndAutogeneratedName() {
        PayrollRun input = new PayrollRun();
        input.setOrganizationId(orgId);
        input.setPayPeriodStart(LocalDate.of(2026, 4, 1));
        input.setPayPeriodEnd(LocalDate.of(2026, 4, 30));
        input.setPaymentDate(LocalDate.of(2026, 5, 5));
        input.setRunName(" ");

        when(payrollRunRepository.save(any(PayrollRun.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        PayrollRun created = payrollService.createPayrollRun(input);

        assertThat(created.getStatus()).isEqualTo("DRAFT");
        assertThat(created.getEmployeeCount()).isZero();
        assertThat(created.getRunName()).contains("Payroll 2026-04-01 - 2026-04-30");
        assertThat(created.getTotalGrossPay()).isNotNull();
        assertThat(created.getTotalDeductions()).isNotNull();
        assertThat(created.getTotalNetPay()).isNotNull();
    }
}
