--liquibase formatted sql

--changeset easyops:hosp-033-aurora-hospital-org-seed
--comment: Seed admin.organizations for Aurora Specialized Hospital (demo). Logo URL can be replaced. Re-runnable. Link users via admin.user_organizations so GET /api/organizations/me returns this tenant.

-- Stable id for references in docs and optional user_organizations links
INSERT INTO admin.organizations (
    id,
    code,
    name,
    legal_name,
    description,
    logo,
    website,
    email,
    phone,
    industry,
    business_type,
    tax_id,
    registration_number,
    fiscal_year_start,
    currency,
    timezone,
    locale,
    address_line1,
    address_line2,
    city,
    state,
    postal_code,
    country,
    subscription_plan,
    subscription_status,
    subscription_start_date,
    max_users,
    max_storage,
    status,
    is_active,
    created_at,
    updated_at
) VALUES (
    'a1b2c3d4-e5f6-4789-a012-a1b2c3d4e5f6'::uuid,
    'ASHK',
    'Aurora Specialized Hospital',
    'Aurora Specialized Hospital Ltd.',
    'Multi-specialty hospital',
    'aurora.png',
    'https://www.aurora.hospital/',
    'info@aurora.hospital',
    '09610-989998',
    'Healthcare',
    'Hospital',
    NULL,
    NULL,
    NULL,
    'BDT',
    'Asia/Dhaka',
    'en-US',
    '19/1, Kakrail',
    'Kakrail',
    'Dhaka',
    'Dhaka',
    '1000',
    'BD',
    'ENTERPRISE',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    500,
    10737418240,
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    legal_name = EXCLUDED.legal_name,
    description = EXCLUDED.description,
    logo = EXCLUDED.logo,
    website = EXCLUDED.website,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    industry = EXCLUDED.industry,
    business_type = EXCLUDED.business_type,
    address_line1 = EXCLUDED.address_line1,
    address_line2 = EXCLUDED.address_line2,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    postal_code = EXCLUDED.postal_code,
    country = EXCLUDED.country,
    currency = EXCLUDED.currency,
    timezone = EXCLUDED.timezone,
    locale = EXCLUDED.locale,
    subscription_plan = EXCLUDED.subscription_plan,
    subscription_status = EXCLUDED.subscription_status,
    max_users = EXCLUDED.max_users,
    max_storage = EXCLUDED.max_storage,
    status = EXCLUDED.status,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;

--rollback DELETE FROM admin.organizations WHERE code = 'ASHK';
