--liquibase formatted sql

-- FR-P1.7 / FR-P1.2 Phase 1: Add allergy-match metadata columns to ehr.prescription_allergy_checks.
--
-- match_type  — which matching heuristic fired (DIRECT, SYNONYM, DRUG_COMPONENT, DRUG_CLASS, CROSS_REACTIVITY).
--               CROSS_REACTIVITY entries are clinical warnings, not confirmed allergies.
-- clinical_note — prescriber-facing explanation of why the alert was raised (generated by AllergyMatchingService).
--
-- LIQUIBASE ID LOCK (Gap N3): This file is named 047-*.sql but the changeset id below uses prefix 046.
-- The id is frozen: deployed databases record hospital-service:046-prescription-allergy-check-match-type.
-- Do NOT rename the id to 047-... — Liquibase would execute this block again and fail on existing columns.
-- See db/changelog/README-LIQUIBASE-CHANGESET-IDS.md

--changeset hospital-service:046-prescription-allergy-check-match-type
ALTER TABLE ehr.prescription_allergy_checks
    ADD COLUMN IF NOT EXISTS match_type   VARCHAR(30),
    ADD COLUMN IF NOT EXISTS clinical_note TEXT;

COMMENT ON COLUMN ehr.prescription_allergy_checks.match_type IS
    'FR-P1.7 Phase 1: How the allergy was matched. Values: DIRECT, SYNONYM, DRUG_COMPONENT, DRUG_CLASS, CROSS_REACTIVITY.';
COMMENT ON COLUMN ehr.prescription_allergy_checks.clinical_note IS
    'Prescriber-facing explanation of the match (e.g. cross-reactivity mechanism, synonym pair, class membership).';
