name: Aurora HMS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # -------------------------
      # Checkout code
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # Build project
      # -------------------------
      - name: Build Spring Boot project
        working-directory: easyops-erp
        run: mvn clean package -DskipTests

      # -------------------------
      # List JARs (debug)
      # -------------------------
      - name: List JAR files
        working-directory: easyops-erp
        run: Get-ChildItem -Recurse -Filter *.jar

      # -------------------------
      # Deploy Eureka to VM
      # -------------------------
      - name: Deploy Eureka
        shell: powershell
        run: |
          scp easyops-erp/services/eureka/target/*.jar til@192.168.40.111:~/aurora-hms/eureka/app.jar

      # -------------------------
      # Restart Eureka on VM
      # -------------------------
      - name: Restart Eureka
        shell: powershell
        run: |
           ssh til@192.168.40.111 "pkill -f eureka || true"
           ssh til@192.168.40.111 "nohup java -jar ~/aurora-hms/eureka/app.jar > ~/aurora-hms/eureka/eureka.log 2>&1 &"