name: Aurora HMS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # -------------------------
      # 1. Checkout code
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # 2. Debug structure
      # -------------------------
      - name: Show repository structure
        run: dir

      # -------------------------
      # 3. Build all services
      # -------------------------
      - name: Build Spring Boot project
        working-directory: easyops-erp
        run: mvn clean package -DskipTests

      # -------------------------
      # 4. Show generated JARs (debug)
      # -------------------------
      - name: List generated JARs
        working-directory: easyops-erp
        run: Get-ChildItem -Recurse -Filter *.jar

      # -------------------------
      # 5. Copy API Gateway JAR to VM
      # -------------------------
      - name: Deploy Eureka to VM
        shell: powershell
        run: |
          scp "C:\work\aurora-hms\actions-runner\actions-runner-win-x64-2.334.0\_work\aurora-hms\aurora-hms\easyops-erp\services\eureka\target\*.jar" til@192.168.40.111:~/aurora-hms/eureka/app.jar

      # -------------------------
      # 6. Restart service on VM
      # -------------------------
      - name: Restart Eureka on VM
        shell: powershell
        run: |
          ssh til@192.168.40.111 << 'EOF'
            echo "Stopping old API Gateway..."
            pkill -f api-gateway || true

            echo "Starting new API Gateway..."
            nohup java -jar ~/aurora-hms/eureka/app.jar > ~/aurora-hms/eureka/app.log 2>&1 &

            echo "Eureka Deployment completed"
          EOF