name: Aurora HMS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show repo structure (DEBUG)
        run: dir

      - name: Move into project folder
        run: cd easyops-erp

      - name: Build project
        run: mvn clean package -DskipTests
        working-directory: easyops-erp